### ISSUE TITLE
请问控制器为什么要直接从模型中获取数据呢？这件事不应该articleService调用repository完成吗？

### ISSUE THREAD

**Issue by ByteByteDance** [kevinyan815/laravel_best_practices_cn#1]
您好！很幸运能读到您写的这些文章，您的文章给了我很大的帮助，但有一点我不大明白，您说Controller的职责应该是接收请求、验证请求、调用单一或者多个Service方法完成业务逻辑、返回响应，我很赞同，但我看您的示例代码，控制器中直接调用了model获取文章详情，您看文章详情是不是应该封装在service中获取呢？以下是我复制的controller一章中的代码。希望能得到您的指教，谢谢！
`controller 的职责
Controller的职责应该是接收请求、验证请求、调用单一或者多个Service方法完成业务逻辑、返回响应。

class ArticleController extends Controller
{
    public function setArticleOff(Request $request, ArticleService $artService)
    {
        ...//表单验证

        $article = Article::find($request->get('article_id'));//这一行，是否应该放到service中？
         $this->articleService->setArticleOffline($article);

        ...//返回响应给客户端
    }
}`

**Comment by kevinyan815** [comment]
首先感谢你能这么仔细的阅读我写的东西， 我在开头写过随着时间推移对软件开发的理解会不停变化，所以有可能推翻这些自己列最佳实践。 文章里的文字是很久后改过的，但是示例是在没时间就没改。在文章里也做了文字说明。   根据文字里最后的描述，查询应该封装在`Respository`中， 用`Service`再调用`Respository`。 对于小项目来说加`Repository`这一层有点繁琐，但长期来看还是给项目带来了更多可配置的自由度。

可以参考我做的这个脚手架 https://github.com/kevinyan815/laravel-bootstrapper 

目前很少用PHP和Laravel，所以也很少有时间更新这些。 如果你觉得理解比较透彻了可以尝试写一个示例Merge到文章里。

**Comment by ByteByteDance** [comment]
> 首先感谢你能这么仔细的阅读我写的东西， 我在开头写过随着时间推移对软件开发的理解会不停变化，所以有可能推翻这些自己列最佳实践。 文章里的文字是很久后改过的，但是示例是在没时间就没改。在文章里也做了文字说明。 根据文字里最后的描述，查询应该封装在`Respository`中， 用`Service`再调用`Respository`。 对于小项目来说加`Repository`这一层有点繁琐，但长期来看还是给项目带来了更多可配置的自由度。
> 
> 可以参考我做的这个脚手架 https://github.com/kevinyan815/laravel-bootstrapper
> 
> 目前很少用PHP和Laravel，所以也很少有时间更新这些。 如果你觉得理解比较透彻了可以尝试写一个示例Merge到文章里。

谢谢指教！我好好学习下您发的这个脚手架。好的，等我理解透彻了就尝试写一个示例。
